import chromadb
from chromadb.config import Settings

client = chromadb.PersistentClient(path="./chroma_db")
collection = client.get_or_create_collection("chatfaq")

faqs= [
    {"question": "How can I check my Vi balance?", "answer": "You can check your Vi balance by dialing *199# from your Vi number or using the MyVi app."},
    {"question": "How do I recharge my Vi prepaid number?", "answer": "Recharge online via the MyVi app, Vi website, or authorized retailers."},
    {"question": "How to activate Vi services after recharge?", "answer": "Services activate automatically after recharge. Restart your phone if not active."},
    {"question": "What are the 4G/5G availability details?", "answer": "Check 4G/5G coverage on the Vi website or MyVi app based on your location."},
    {"question": "How do I port my number to Vi?", "answer": "Send SMS ‘PORT <mobile number>’ to 1900 to initiate porting to Vi."},
    {"question": "How can I activate international roaming on my Vi number?", "answer": "Activate via MyVi app or customer care; may take up to 24 hours."},
    {"question": "What should I do if I lost my Vi SIM card?", "answer": "Visit a Vi store with valid ID for SIM replacement."},
    {"question": "How do I check my Vi call history?", "answer": "View call history in the MyVi app under usage details."},
    {"question": "What are the data rollover policies for Vi prepaid plans?", "answer": "Unused data rolls over as per plan terms for select prepaid plans."},
    {"question": "How can I change my Vi prepaid plan?", "answer": "Recharge with a new plan via MyVi app or website."},
    {"question": "How do I check my Vi postpaid bill?", "answer": "View and pay bills on the MyVi app or Vi website."},
    {"question": "How can I activate DND (Do Not Disturb) on my Vi number?", "answer": "Send SMS START 0 to 1909 or configure on Vi website."},
    {"question": "How do I know my Vi prepaid plan’s validity?", "answer": "Dial *199# or check in the MyVi app."},
    {"question": "What are the customer care numbers for Vi?", "answer": "Call 199 (from Vi) or 1800-419-9999 (toll-free)."},
    {"question": "Can I use my Vi SIM in any device?", "answer": "Yes, it works on all GSM-compatible devices."},
    {"question": "How can I block my Vi number temporarily?", "answer": "Contact Vi customer care or visit a store to request suspension."},
    {"question": "How do I check my data usage on Vi?", "answer": "Check usage via MyVi app, *199#, or website."},
    {"question": "What documents are required to get a new Vi SIM?", "answer": "Valid ID and address proof documents as per regulations."},
    {"question": "How can I upgrade my Vi SIM to 4G or 5G?", "answer": "Visit Vi store with old SIM and ID for upgrade."},
    {"question": "What do I do if my Vi SIM is not getting network?", "answer": "Restart phone, check network status, or contact customer care."},
    {"question": "How to activate Vi caller tune?", "answer": "Use the MyVi app or SMS to activate caller tunes."},
    {"question": "Can I transfer my Vi number to another person?", "answer": "No, mobile number portability is only between operators, not transferable to another person."},
    {"question": "How to check my Vi prepaid plan benefits?", "answer": "Check plan benefits in the MyVi app or website."},
    {"question": "How do I update my KYC details for Vi?", "answer": "Visit nearest Vi store with valid ID for KYC update."},
    {"question": "What is the validity of Vi prepaid plans?", "answer": "Plan validity varies; check details during recharge or in MyVi app."},
    {"question": "How can I deactivate a Vi service?", "answer": "Call customer care or use MyVi app to deactivate specific services."},
    {"question": "What is Vi’s refund policy?", "answer": "Refunds are processed as per TRAI and company policy for recharge failures."},
    {"question": "How do I get Vi customer care support online?", "answer": "Use the MyVi app chat support or Vi website support section."},
    {"question": "How to check remaining validity on my Vi prepaid account?", "answer": "Dial *199# or check MyVi app."},
    {"question": "Can I use Vi SIM outside India?", "answer": "Yes, if international roaming is activated and supported in that country."},
    {"question": "How to activate Vi 5G services?", "answer": "5G is automatically activated if you have a 5G SIM and are in 5G coverage."},
    {"question": "How do I get duplicate Vi SIM?", "answer": "Visit Vi store with ID proof for duplicate SIM."},
    {"question": "What is Vi’s policy on missed call alerts?", "answer": "Missed call alerts are free and activated by default."},
    {"question": "Can I block unwanted calls on Vi?", "answer": "Activate DND or use phone’s native blocking features."},
    {"question": "How to check my Vi prepaid recharge history?", "answer": "Check recharge history on MyVi app or by calling customer care."},
    {"question": "What are Vi’s roaming charges?", "answer": "Roaming charges vary by circle and country; check rates on Vi website."},
    {"question": "How to activate Vi SMS pack?", "answer": "Recharge with an SMS pack via MyVi app or website."},
    {"question": "How to port my Vi number to another operator?", "answer": "Send SMS PORT <your number> to 1900 and follow the steps."},
    {"question": "Can I link multiple devices to one Vi number?", "answer": "No, one SIM supports one device at a time."},
    {"question": "How to check my Vi prepaid data balance?", "answer": "Dial *199# or check on MyVi app."},
    {"question": "How can I get Vi broadband connection?", "answer": "Visit Vi website or contact customer care to apply."},
    {"question": "Does Vi support eSIM?", "answer": "Yes, eSIM support is available in select cities and devices."},
    {"question": "How to use Vi Wi-Fi Calling?", "answer": "Enable Wi-Fi calling in phone settings; available in supported areas."},
    {"question": "What is Vi’s refund timeline?", "answer": "Refunds are typically processed within 7 working days."},
    {"question": "How to update my contact details with Vi?", "answer": "Update details at Vi store with valid proof or via customer care."},
    {"question": "Can I get a duplicate Vi postpaid bill?", "answer": "Yes, via MyVi app or customer care."},
    {"question": "How do I deactivate Vi services like voicemail?", "answer": "Call customer care or use MyVi app to manage services."},
    {"question": "What to do if my Vi number is hacked or misused?", "answer": "Immediately contact Vi customer care and file a complaint."},
    {"question": "How do I activate Vi prepaid plan benefits?", "answer": "Recharge with a valid plan; benefits activate automatically."},
    {"question": "Does Vi offer family or group plans?", "answer": "Yes, Vi offers combo and family plans; check details on website."},
    {"question": "How to check Vi customer care working hours?", "answer": "Customer care is available 24/7 at 199 or 1800-419-9999."},
    {"question": "Can I switch from Vi postpaid to prepaid?", "answer": "Yes, visit Vi store or contact customer care for process details."},
    {"question": "How do I check Vi prepaid plan details?", "answer": "Use MyVi app or dial *199# to view plan details."},
    {"question": "What is Vi’s policy on network downtime?", "answer": "Vi strives for minimal downtime; updates are communicated on website."},
    {"question": "How do I change my Vi prepaid plan?", "answer": "Recharge with a new plan voucher or use MyVi app."},
    {"question": "Can I use Vi SIM on multiple devices with the same number?", "answer": "No, one SIM is for one device only."},
    {"question": "How do I activate caller tunes on Vi?", "answer": "Use MyVi app or SMS service to activate caller tunes."},
    {"question": "How to check Vi prepaid plan validity?", "answer": "Dial *199# or check on MyVi app."},
    {"question": "What are Vi’s data pack options?", "answer": "Vi offers various data packs; see MyVi app or website for plans."},
    {"question": "How do I get Vi customer care number?", "answer": "Dial 199 from Vi number or 1800-419-9999 toll-free."},
    {"question": "What is Vi’s refund policy for recharge failures?", "answer": "Refunds are processed as per TRAI guidelines and may take up to 7 days."},
    {"question": "How to block unwanted calls on Vi?", "answer": "Activate DND by sending SMS START 0 to 1909."},
    {"question": "How to check remaining talk time on Vi prepaid?", "answer": "Dial *199# or check in MyVi app."},
    {"question": "How to activate Vi international roaming?", "answer": "Contact customer care or use MyVi app for activation."},
    {"question": "How to report a lost or stolen Vi SIM?", "answer": "Immediately call customer care to block your SIM and get a replacement."},
    {"question": "How to check Vi postpaid bill payment history?", "answer": "Available on MyVi app or website."},
    {"question": "How do I reset my MyVi app password?", "answer": "Use the 'Forgot Password' option in the app or website."},
    {"question": "Can I get a Vi SIM without physical documents?", "answer": "No, KYC documents are mandatory as per government regulations."},
    {"question": "How to update my address in Vi records?", "answer": "Visit a Vi store with valid address proof."},
    {"question": "How do I activate a new Vi SIM?", "answer": "Insert the SIM, restart your phone, and complete the tele-verification by calling 59059."},
    {"question": "How to port to Vi from another network?", "answer": "Send 'PORT <Your Mobile Number>' to 1900. You'll get a UPC code. Submit this at a Vi store with valid ID proof."},
    {"question": "What documents are required for new SIM activation?", "answer": "You need a government-issued ID proof like Aadhaar, PAN, or Voter ID."},
    {"question": "How to upgrade to a 4G SIM in Vi?", "answer": "Visit a Vi store with your ID proof and existing SIM. Request a 4G SIM upgrade."},
    {"question": "How can I check my Vi balance?", "answer": "Dial *199# or use the Vi app to check data, talktime, and SMS balance."},
    {"question": "What happens if my recharge fails?", "answer": "If your amount is debited but recharge fails, it is usually refunded within 3–5 business days."},
    {"question": "Can I recharge someone else’s Vi number?", "answer": "Yes, use the Vi app or any UPI app to recharge another Vi number."},
    {"question": "How to get a recharge loan on Vi?", "answer": "Dial *199# and select 'Loan Recharge' under special offers if eligible."},
    {"question": "How to activate Vi internet settings?", "answer": "Send ‘ALL’ to 199 to get the internet settings. Save and apply them."},
    {"question": "Why is my Vi internet slow?", "answer": "Network congestion, weak signal, or data cap limits can slow down speed. Try restarting your device."},
    {"question": "How to check data usage in Vi?", "answer": "Open the Vi app or dial *199*2*2# to view remaining data."},
    {"question": "Does Vi offer unlimited data?", "answer": "Yes, select prepaid and postpaid plans include unlimited night or weekend data."},
    {"question": "How to activate international roaming on Vi?", "answer": "You can activate it via the Vi app or by sending an SMS ‘IRACT’ to 199."},
    {"question": "Are there roaming packs for the USA and UK?", "answer": "Yes, Vi offers international roaming packs for various countries including the USA, UK, UAE, etc."},
    {"question": "Can I use my Vi number outside India without a roaming pack?", "answer": "Without a roaming pack, you may incur high charges. It's recommended to activate a pack."},
    {"question": "How to check IR pack validity?", "answer": "Log into the Vi app and check under 'International Roaming'."},
    {"question": "How to log into the Vi app?", "answer": "Download the app and log in using your Vi number and OTP."},
    {"question": "Can I manage multiple Vi numbers in the app?", "answer": "Yes, you can add and manage multiple numbers via a single login."},
    {"question": "How to reset Vi app password?", "answer": "There is no password. You log in with OTP sent to your Vi number."},
    {"question": "How to download my Vi postpaid bill?", "answer": "Log into the Vi app or website, go to 'Bills and Payments' and download the PDF."},
    {"question": "What if I miss my Vi postpaid bill due date?", "answer": "A late fee might apply. You’ll receive reminders via SMS and email."},
    {"question": "How to change Vi postpaid plan?", "answer": "Use the Vi app or contact customer support to change your plan."},
    {"question": "How to check active offers on my Vi number?", "answer": "Dial *199# or check the 'Offers' section in the Vi app."},
    {"question": "How to unsubscribe from Vi VAS services?", "answer": "Send 'STOP' to 155223 to unsubscribe from Value-Added Services."},
    {"question": "Is Vi offering free OTT subscriptions?", "answer": "Yes, select plans offer Disney+ Hotstar, SonyLIV, and others as bundled benefits."},
    {"question": "How to block a lost Vi SIM?", "answer": "Call customer care or visit a Vi store to block and replace your SIM."},
    {"question": "Can I get a Vi eSIM?", "answer": "Yes, eSIM is available for supported devices. Send 'eSIM <email>' to 199 to start the activation process."},
    {"question": "How to file a network complaint in Vi?", "answer": "Use the Vi app or call 198 to raise a service/network complaint."},
    {"question": "How to contact Vi customer care?", "answer": "Dial 198 or 199 from your Vi number, or use chat support in the Vi app."},
    {"question": "Does Vi provide customer care support in regional languages?", "answer": "Yes, support is available in multiple regional languages."},
    {"question": "How to know if my device is compatible with Vi 5G?", "answer": "Check device compatibility on the Vi website or with customer care."},
    {"question": "How do I activate Vi voicemail service?", "answer": "Call customer care or dial the specific short code available on the Vi website."},
    {"question": "What is Vi Movies & TV?", "answer": "Vi Movies & TV is an OTT platform for Vi users offering movies, TV shows, and live TV."},
    {"question": "How do I change my registered email ID with Vi?", "answer": "Log into your Vi account and update the email ID under account settings or contact support."},
    {"question": "Can I pause my Vi prepaid plan?", "answer": "No, prepaid plans cannot be paused. You can opt for minimum recharge to keep the number active."},
    {"question": "What to do if my Vi number is flagged for spam?", "answer": "Contact customer care to raise a de-flagging request and avoid promotional messages."},
    {"question": "Can I use Vi services while travelling on a cruise?", "answer": "Vi doesn’t support maritime roaming; use Wi-Fi or international roaming services if available."},
    {"question": "How can I remove value-added services (VAS) on my Vi number?", "answer": "Send ‘STOP’ to 155223 or use the MyVi app to manage services."},
    {"question": "How to activate Vi OTT subscription offers?", "answer": "Recharge with eligible plans and follow the instructions in the MyVi app to activate offers like Disney+ Hotstar, SonyLIV, etc."},
    {"question": "What are the data roaming charges on international roaming?", "answer": "Charges vary by country. Visit the Vi website or app to view country-specific roaming data rates."},
    {"question": "What should I do if I am not able to use data services while on international roaming?", "answer": "Ensure data roaming is enabled in your phone settings. Restart the device, and if issues persist, contact Vi customer care."},
    {"question": "How to enable data roaming on my device?", "answer": "Go to Settings > Network & Internet > Mobile Network > Enable 'Data Roaming'."},
    {"question": "Are incoming SMS free while on international roaming?", "answer": "Yes, incoming SMS are free while roaming internationally."},
    {"question": "Will my SIM work in all countries?", "answer": "Vi SIMs work in most countries with roaming agreements. Check the Vi website for the list of supported countries."},
    {"question": "What should I do before traveling abroad with my Vi SIM?", "answer": "Activate an international roaming pack, enable roaming in settings, and ensure your SIM is roaming-enabled."},
    {"question": "Can I receive OTPs abroad on international roaming?", "answer": "Yes, you can receive OTPs abroad as long as roaming is active."},
    {"question": "Is there a validity extension pack for international roaming?", "answer": "Yes, Vi offers IR validity extension packs. Check availability in the app or website."},
    {"question": "What is Vi Hero Unlimited?", "answer": "It’s a plan feature that offers weekend data rollover, night binge (12am–6am), and data delights for select unlimited plans."},
    {"question": "How to activate Vi Hero Unlimited benefits?", "answer": "Recharge with an eligible Hero Unlimited plan via the Vi app, website, or retailer."},
    {"question": "What is Vi Movies & TV?", "answer": "It’s a Vi app feature that gives access to movies, live TV, and shows for select Vi customers."},
    {"question": "How to redeem Vi rewards?", "answer": "Log in to the Vi app, go to the 'Rewards' section, and select offers to redeem your earned coins."},
    {"question": "How to switch from Vi postpaid to prepaid?", "answer": "Visit a Vi store with your ID proof and request to migrate from postpaid to prepaid."},
    {"question": "Can I transfer balance to another Vi number?", "answer": "Balance transfer is not generally allowed. However, you can recharge another number through the app or USSD."},
    {"question": "What to do if I accidentally recharged the wrong number?", "answer": "Contact Vi customer care immediately. Reversals are not guaranteed but may be considered in some cases."},
    {"question": "Does Vi support 5G services?", "answer": "Vi is rolling out 5G in select cities. Check the Vi website or app to see coverage in your area."},
    {"question": "How to activate Vi 5G?", "answer": "No special activation is needed. Just insert your Vi SIM in a 5G-enabled phone in a 5G coverage area."},
    {"question": "How to share data with other Vi users?", "answer": "Currently, Vi does not support direct data sharing between users."},
    {"question": "What is weekend data rollover?", "answer": "It allows unused data from weekdays to be carried over and used on weekends in Hero Unlimited plans."},
    {"question": "How to block spam calls and SMS on Vi?", "answer": "Activate DND (Do Not Disturb) by sending ‘START 0’ to 1909 or via the Vi app."},
    {"question": "How to check Vi network coverage?", "answer": "Use the Vi app or website to view 4G and 5G coverage maps for your location."},
    {"question": "What is Vi Tunes?", "answer": "Vi Tunes lets you set caller tunes. Activate via the Vi app or by sending SMS to 56789."},
    {"question": "How to deactivate Vi Tunes?", "answer": "Send ‘STOP’ to 155223 or use the Vi app to unsubscribe from caller tunes."},
    {"question": "How to request SIM delivery at home?", "answer": "Visit the Vi website and select the home delivery option during SIM purchase or port-in."},
    {"question": "How long does it take to activate a new Vi SIM?", "answer": "It typically activates within a few hours post KYC. In some cases, up to 24 hours."}
]

questions = [faq['question'] for faq in faqs]
answers = [faq['answer'] for faq in faqs]

collection.add(
    documents=answers,       
    metadatas=[{"question": q} for q in questions],  
    ids=[f"faq_{i}" for i in range(len(faqs))]      
)

print("Number of documents in collection:", collection.count())